version: '3.8'
services:
  alpha-tifo:
    container_name: alpha-tifo
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - 'traefik.enable=true'
      #Routers
      - "traefik.http.routers.alpha-tifo.rule=Host(`alpha-tifo.julian-husson.com`)"
      - "traefik.http.routers.alpha-tifo.entrypoints=websecure"
      - "traefik.http.routers.alpha-tifo.tls.certresolver=resolver"
      - "traefik.http.routers.alpha-tifo.middlewares=rate-limit"
      #Services
      - "traefik.http.services.alpha-tifo.loadbalancer.server.port=3000"
      #Middlewares
      - "traefik.http.middlewares.rate-limit.ratelimit.average=5"
      - "traefik.http.middlewares.rate-limit.ratelimit.burst=10"
    networks:
      - web
networks:
  web:
    external: true